import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BottomNavigationBar from "@/components/bottom-navigation-bar";
import StoreProvider from "@/components/StoreProvider";
import AlertCustom from "@/components/alert-custom";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Th Budget Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <AlertCustom 
            title={ "Expense" }
            message={ "Add expense success" }
          /> */}
          <div
            style={{ backgroundColor: "#f7f7f7" }}
          >
            {children}
          </div>
          <BottomNavigationBar/>
        </body>
      </html>
    </StoreProvider>
  );
}
